project:
  type: website
  render:
    - index.qmd
    - dance.qmd
    - sizeclass.qmd
    - gmraw.qmd
    - gmszclass.qmd

website:
  title: "supplementary materials"
  margin-header: |
    ![](/images/slab.png)
  navbar:
    logo: "sfasu.png"
    left:
      - href: index.qmd
        text: Home
      - dance.qmd
      - sizeclass.qmd
      - gmraw.qmd
      - gmszclass.qmd
    right:
      - icon: github
        href: https://github.com/seldenlab/elliptical.bifaces
        aria-label: GitHub

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

