project:
  type: website

website:
  title: "elliptical.bifaces"
  image: slab.png
  margin-header: |
    ![](/images/slab.png)
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sizeclass.qmd
      - gmraw.qmd
      - gmszclass.qmd
    right:
      - icon: github
        href: https://github.com/seldenlab/elliptical.bifaces
        aria-label: GitHub

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

