project:
  type: website

website:
  title: "elliptical.bifaces"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sizeclass.qmd
      - gmraw.qmd
      - gmszclass.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

